services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    restart: unless-stopped
    #network_mode: host
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 3001:3000/tcp
      - 90:80/tcp
    volumes:
      - /mnt/data/service/adguardhome/work:/opt/adguardhome/work
      - /mnt/data/service/adguardhome/conf:/opt/adguardhome/conf
networks: {}
